package com.rfizzle.mercantile.contract;

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import net.minecraft.core.UUIDUtil;
import net.minecraft.resources.ResourceLocation;

import java.util.UUID;

/**
 * One delivery contract riding a villager's attachment (issue #86). A contract is first rolled as
 * an <em>offer</em> ({@code accepted=false}, signalled by the speech-bubble cue); using paper on
 * the villager accepts it ({@code accepted=true}) and hands the player the written contract item.
 * Matching between the item and the villager is by {@link #id} — never by villager UUID, which is
 * regenerated by the pickup/place cycle.
 *
 * <p>{@code expiryGameTime} is the offer-retraction time while un-accepted and the delivery
 * deadline once accepted. The requested item is stored as a {@link ResourceLocation} rather than a
 * registry reference so a datapack removing the item voids this one contract at delivery time;
 * a structurally malformed blob is likewise contained by the lenient field in
 * {@code MercantileVillagerData.CODEC} rather than failing the whole villager-data decode.
 */
public record DeliveryContract(UUID id, ResourceLocation itemId, int count, int payment,
                               boolean accepted, long expiryGameTime) {

    /** Hard bounds on persisted values; a save file is untrusted input. */
    public static final int MAX_COUNT = 1024;
    public static final int MAX_PAYMENT = 4096;

    public static final Codec<DeliveryContract> CODEC = RecordCodecBuilder.create(instance ->
            instance.group(
                    UUIDUtil.CODEC.fieldOf("id").forGetter(DeliveryContract::id),
                    ResourceLocation.CODEC.fieldOf("item").forGetter(DeliveryContract::itemId),
                    Codec.INT.fieldOf("count").forGetter(DeliveryContract::count),
                    Codec.INT.fieldOf("payment").forGetter(DeliveryContract::payment),
                    Codec.BOOL.optionalFieldOf("accepted", false).forGetter(DeliveryContract::accepted),
                    Codec.LONG.optionalFieldOf("expiryGameTime", -1L).forGetter(DeliveryContract::expiryGameTime)
            ).apply(instance, DeliveryContract::new));

    public DeliveryContract {
        count = Math.clamp(count, 1, MAX_COUNT);
        payment = Math.clamp(payment, 0, MAX_PAYMENT);
    }

    public boolean isExpired(long nowGameTime) {
        return expiryGameTime >= 0 && nowGameTime >= expiryGameTime;
    }

    /** Copy of this offer as an accepted contract with the delivery deadline set. */
    public DeliveryContract accept(long deadlineGameTime) {
        return new DeliveryContract(id, itemId, count, payment, true, deadlineGameTime);
    }

    /** The in-game day number the deadline falls on, for player-facing display. */
    public static long deadlineDay(long expiryGameTime) {
        return expiryGameTime / 24_000L;
    }

    /** Pool payments scale by a config percent (100 = as authored). */
    public static int scalePayment(int basePayment, int scalePercent) {
        return Math.clamp((int) ((long) basePayment * scalePercent / 100L), 0, MAX_PAYMENT);
    }
}
